version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
  app:
    build: .
    command: ["sh", "-c", "./wait-for-it.sh postgres:5432 -- npx prisma migrate deploy && npm run seed && npm start"]
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "postgresql://test:test@postgres:5432/test"
