[build]
  command = "npm install && npm run build:netlify"
  functions = "src"
[functions]
  external_node_modules = ["src"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"