name: Deploy Backend to AWS

on:
  push:
    branches: [aws-deploy]

jobs:   
  deploy:
    runs-on: ec2-runner-be
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-be:latest
      - name: Delete old container
        run: docker rm -f notes-app-be
      - name: Run docker container
        run: docker run -e DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -d -p 5000:5000 --name notes-app-be push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-be:latest