name: Backend e2e Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: http://localhost:5000
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Create .env file
      run: |
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: Start service in docker
      run: |
        yarn docker:up

    - name: Wait for service to start
      run: |
          sleep 15

    - name: Print application logs
      run: docker-compose logs

    - name: Test connectivity
      run: curl ${API_URL}

    - name: Run e2e Tests
      run: |
        yarn
        yarn test:e2e

    - name: Stop service in docker
      run: |
        yarn docker:down
