name: Build Backend Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start service in docker
      run: |
        npm run docker:up

    - name: Stop service in docker
      run: |
        npm run docker:down
