name: Backend Integration Tests

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: ./backend

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Integration Tests with Coverage
        run: npm run test:coverage

      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./backend/coverage/lcov.info
