name: Frontend Service Tests - Playwright

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "playwright/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: http://localhost:5000
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Create .env file
      run: | 
        cd ./backend
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env

    - name: Start service in docker
      run: |
        cd ./backend
        npm run docker:up

    - name: Wait for service to start
      run: |
          sleep 15

    - name: Test connectivity
      run: curl ${API_URL}

    - name: Install and start frontend
      run: |
        cd ./frontend
        yarn
        yarn build
        yarn start &

    - name: Install Playwright
      run: |
        cd ./playwright
        npm ci
        npx playwright install chromium

    - name: Run Playwright Tests
      run: |
        cd ./playwright
        npm run test

    - name: Stop service in docker
      run: |
        cd ./backend
        npm run docker:down
