name: Playwright Linting

on:
  pull_request:
    branches: ["main"]
    paths:
      - "playwright/**"

defaults:
  run:
    working-directory: ./playwright

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Install packages
              run: yarn
        
            - name: Run ESLint
              run: yarn lint
