name: Playwright e2e Production Tests

on:
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./playwright

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Playwright
      run: |
        npm ci
        npx playwright install chromium

    - name: Run Playwright Tests
      run: |
        npm run test:production

    - name: Run Playwright Tests
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: ./playwright/playwright-report/
        retention-days: 30
