name: React Component Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./frontend

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install and Execute Component Tests
      run: |
        npm ci
        npm run test:coverage

    - name: Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.19
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./frontend/coverage/lcov.info

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push Docker image
      run: |
          npm run docker:build
          docker tag notes-app-fe:latest ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-fe:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app-fe:latest
