name: React Component Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./frontend

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install and Execute Component Tests
      run: |
        npm ci
        npm run test:coverage

    - name: Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./frontend/coverage/lcov.info
