name: React Testing Library Component Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Change to frontend directory
      run: cd frontend

    - name: Install Packages and Execute Component Tests
      run: |
        npm install
        npm run test
